$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectDir = Split-Path -Parent $ScriptDir

# Read config
$Config = Get-Content "$ProjectDir\config\runtime.json" | ConvertFrom-Json
$SourcePath = $Config.source_path

$Now = Get-Date -Format "yyyyMMdd_HHmm"
$BuildLog = "$ProjectDir\logs\build\$Now.log"

function Write-Log($msg) {
    $line = "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  $msg"
    Add-Content -Path $BuildLog -Value $line
    Write-Host $msg
}

Write-Log "============================================"
Write-Log "=== FULL BUILD (full re-index + LLM) ==="
Write-Log "============================================"
Write-Log "project: $ProjectDir"
Write-Log "source: $SourcePath"

Write-Host ""
Write-Host "=== GITNEXUS (full) ==="

try {
    Push-Location $SourcePath
    gitnexus analyze . --skills -f 2>&1 | Tee-Object -FilePath "$ProjectDir\logs\graph\$Now-gitnexus.log" | Out-Host
    Pop-Location
    # Sync gitnexus output to knowledge/
    $GitNexusSrc = "$SourcePath\.claude\skills"
    $GitNexusDst = "$ProjectDir\knowledge\gitnexus"
    if (Test-Path $GitNexusSrc) {
        New-Item -ItemType Directory -Force -Path $GitNexusDst | Out-Null
        Copy-Item -Recurse -Force "$GitNexusSrc\*" $GitNexusDst
        Write-Log "gitnexus: synced to knowledge/gitnexus/"
    }
    Write-Log "gitnexus: done"

    # Build CLAUDE.md: merge AI-Runtime section with gitnexus section
    $ClaudeMd = "$SourcePath\CLAUDE.md"
    $TemplateClaudeMd = "$ProjectDir\CLAUDE.md"
    # Fallback: read from project dir's own CLAUDE.md (copied during bootstrap)
    if (-not (Test-Path $TemplateClaudeMd)) {
        $TemplateClaudeMd = "$ProjectDir\CLAUDE.md"
    }
    $ProjectName = $Config.project_name
    if (-not $ProjectName) {
        $ProjectName = Split-Path $SourcePath -Leaf
    }

    # Read AI-Runtime template section (everything between <!-- AI-Runtime:start --> and <!-- AI-Runtime:end -->)
    if (Test-Path $TemplateClaudeMd) {
        $TemplateContent = Get-Content $TemplateClaudeMd -Raw
        if ($TemplateContent -match '(?s)<!-- AI-Runtime:start -->(.*?)<!-- AI-Runtime:end -->') {
            $AiRuntimeSection = $Matches[1] -replace '\{\{PROJECT_NAME\}\}', $ProjectName
        }
    }

    if (-not $AiRuntimeSection) {
        # Fallback: minimal AI-Runtime section
        $AiRuntimeSection = @"

# $ProjectName — AI Runtime Build Rules

## Build Modes

| Mode | Command | When |
|------|---------|------|
| **Full** | `full_build.ps1` | Doc/image/config changes, new project init |
| **Incremental** | `incremental_build.ps1` | Code-only changes |

Quick rule: `*.md` / `*.png` / `*.json` / `*.yaml` / directory changes → full build. Pure code (`*.py` / `*.ts`) → incremental.

## Knowledge Artifacts

Full architecture, module overview, and per-file summaries at `knowledge/context.md`.
Per-module key files, entry points, and execution flows at `knowledge/gitnexus/generated/<module>/SKILL.md`.

"@
    }

    if (Test-Path $ClaudeMd) {
        $Existing = Get-Content $ClaudeMd -Raw
        if ($Existing -match '<!-- AI-Runtime:start -->') {
            # Replace existing AI-Runtime section
            $Merged = $Existing -replace '(?s)<!-- AI-Runtime:start -->.*?<!-- AI-Runtime:end -->', "<!-- AI-Runtime:start -->$AiRuntimeSection<!-- AI-Runtime:end -->"
        } else {
            # Prepend AI-Runtime section before gitnexus block
            $Merged = "<!-- AI-Runtime:start -->$AiRuntimeSection`n<!-- AI-Runtime:end -->`n`n$Existing"
        }
    } else {
        # Create new CLAUDE.md with both sections
        $Merged = "<!-- AI-Runtime:start -->$AiRuntimeSection`n<!-- AI-Runtime:end -->`n`n<!-- gitnexus:start -->`n<!-- This section is auto-generated by gitnexus. -->`n<!-- gitnexus:end -->`n"
    }
    Set-Content -Path $ClaudeMd -Value $Merged
    Write-Log "CLAUDE.md: merged AI-Runtime + gitnexus sections"

    # Also sync merged CLAUDE.md back to AI-Runtime project
    Copy-Item -Force $ClaudeMd "$ProjectDir\CLAUDE.md"
    Write-Log "CLAUDE.md: synced to AI-Runtime project"
} catch {
    Write-Log "gitnexus: skipped (not available)"
}

Write-Host ""
Write-Host "=== GRAPHIFY (full + LLM) ==="

try {
    if (-not $env:DEEPSEEK_API_KEY) {
        $env:DEEPSEEK_API_KEY = "sk-3facbf6bbbbc425499adef7f1b9038e5"
    }
    Push-Location $SourcePath
    graphify extract . --backend deepseek --out "$ProjectDir\knowledge" 2>&1 | Tee-Object -FilePath "$ProjectDir\logs\graph\$Now-graphify.log" | Out-Host
    Pop-Location
    Write-Log "graphify: done"
} catch {
    Write-Log "graphify: skipped (not available)"
}

Write-Host ""
Write-Host "=== SUMMARIES ==="

python "$ProjectDir\scripts\generate_summaries_from_graph.py" 2>&1 | ForEach-Object {
    Add-Content -Path $BuildLog -Value $_
    Write-Host $_
}
Write-Log "summaries: done"

Write-Host ""
Write-Host "=== CUSTOM GRAPH ==="

python "$ProjectDir\scripts\graph_builder.py" 2>&1 | Tee-Object -FilePath "$ProjectDir\logs\graph\$Now-graph.log" | Out-Host
Write-Log "graph_builder: done"

Write-Host ""
Write-Host "=== CONTEXT ==="

python "$ProjectDir\scripts\generate_knowledge_artifacts.py" 2>&1 | ForEach-Object {
    Add-Content -Path $BuildLog -Value $_
    Write-Host $_
}
Write-Log "context: done"

Write-Host ""
Write-Host "=== TEST GAP ==="

python "$ProjectDir\scripts\test_gap.py" 2>&1 | ForEach-Object {
    Add-Content -Path $BuildLog -Value $_
    Write-Host $_
}
Write-Log "test-gap: done"

# Runtime log
$RuntimeLog = "$ProjectDir\logs\runtime\$Now.log"
@"
build: full
timestamp: $Now
source: $SourcePath
branch: $($Config.branch)
build_log: $BuildLog
"@ | Set-Content -Path $RuntimeLog

Write-Log "============================================"
Write-Log "=== FULL BUILD COMPLETE ==="
Write-Log "============================================"
Write-Log "build log: $BuildLog"
